const express = require('express');
const { randomBytes } = require('node:crypto');
const Review = require('../models/RecipeReview');
const Recipe = require('../models/Recipe');
const Client = require('../models/Client');
const api = require('../services/mealApiService');
const support = require('../services/recipeSupport');
const router = express.Router();

router.use(support.databaseReady);
router.use('/:type/:id', (req, res, next) => { req.reviewType = { local: 'Recipe', external: 'ExternalRecipe' }[req.params.type]; req.reviewRecipeId = support.numericId(req.params.id); if (!req.reviewType || !req.reviewRecipeId) return res.status(400).json({ error: 'สูตรไม่ถูกต้อง' }); next(); });
async function render(req, res) { const key = { recipeType: req.reviewType, recipeId: req.reviewRecipeId }; const client = support.numericId(req.user?._id || req.session?.userId); const [rows, stats, mine] = await Promise.all([Review.find(key).sort({ updatedAt: -1 }).limit(30).populate('client', 'name avatar').lean(), Review.aggregate([{ $match: key }, { $group: { _id: null, rating: { $avg: '$rating' }, count: { $sum: 1 } } }]), client ? Review.findOne({ ...key, client }).lean() : null]); if (client && req.session) req.session.reviewCsrf = req.session.reviewCsrf || randomBytes(32).toString('hex'); res.render('recipes/_reviews', { rows, summary: stats[0] || { rating: 0, count: 0 }, mine, reviewClient: client, reviewToken: req.session?.reviewCsrf || '', reviewPath: '/recipes/reviews/' + req.params.type + '/' + req.params.id }); }
router.get('/:type/:id', support.asyncRoute(render));
router.use('/:type/:id', support.asyncRoute(async (req, res, next) => { const client = support.numericId(req.user?._id || req.session?.userId); if (!client || !await Client.exists({ _id: client })) return res.status(401).json({ error: 'กรุณาเข้าสู่ระบบก่อนรีวิว' }); if (!req.session?.reviewCsrf || req.get('X-CSRF-Token') !== req.session.reviewCsrf) return res.status(403).json({ error: 'ฟอร์มหมดอายุ กรุณาเปิดสูตรใหม่' }); req.reviewClient = client; next(); }));
async function syncRating(type, id) { if (type !== 'Recipe') return; const [stats] = await Review.aggregate([{ $match: { recipeType: type, recipeId: id } }, { $group: { _id: null, rating: { $avg: '$rating' }, count: { $sum: 1 } } }]); await Recipe.updateOne({ _id: id }, { $set: { rating: stats?.rating ?? null, reviewCount: stats?.count || 0 } }); }
router.put('/:type/:id', support.asyncRoute(async (req, res) => { const rating = Number(req.body.rating), comment = req.body.comment; if (!Number.isInteger(rating) || rating < 1 || rating > 5 || typeof comment !== 'string' || comment.length > 2000) return res.status(400).json({ error: 'เลือกคะแนน 1–5 ดาว และข้อความไม่เกิน 2000 ตัวอักษร' }); let exists; if (req.reviewType === 'Recipe') exists = await Recipe.exists({ _id: req.reviewRecipeId }); else { try { exists = await api.lookup(String(req.reviewRecipeId)); } catch (_) { return res.status(502).json({ error: 'ตรวจสอบสูตรไม่สำเร็จ กรุณาลองใหม่' }); } } if (!exists) return res.status(404).json({ error: 'ไม่พบสูตร' }); const key = { client: req.reviewClient, recipeType: req.reviewType, recipeId: req.reviewRecipeId }; let row = await Review.findOne(key); if (row) { row.rating = rating; row.comment = comment; await row.save(); } else { try { await Review.create({ ...key, rating, comment }); } catch (e) { if (e.code !== 11000) throw e; await Review.updateOne(key, { $set: { rating, comment } }); } } await syncRating(req.reviewType, req.reviewRecipeId); await render(req, res); }));
router.delete('/:type/:id', support.asyncRoute(async (req, res) => { await Review.deleteOne({ client: req.reviewClient, recipeType: req.reviewType, recipeId: req.reviewRecipeId }); await syncRating(req.reviewType, req.reviewRecipeId); await render(req, res); }));
module.exports = router;
