const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs/promises'),express=require('express'),mongoose=require('mongoose'),{MongoMemoryServer}=require('mongodb-memory-server'),{chromium}=require('playwright');
let db,server,browser,uploaded;
(async()=>{
 process.env.RECIPE_DEMO_PAYMENTS='true';process.env.NODE_ENV='test';
 db=await MongoMemoryServer.create();await mongoose.connect(db.getUri());await require('../models/Client').collection.insertOne({_id:1,email:'one@example.test',name:'Test chef',role:'chef',bio:'Test bio',institution:'Test school'});
 const app=express();app.set('views',path.resolve('views'));app.set('view engine','ejs');app.use(express.json());app.use(express.urlencoded({extended:false}));app.use(express.static(path.resolve('public')));const session={userId:1};app.use((req,res,next)=>{req.session=session;res.locals.currentUser={_id:1,name:'Test chef',role:'chef'};next()});app.use('/chef/recipes',require('../routes/chefRecipes'));app.use('/recipes',require('../routes/recipes'));app.use('/payments/promptpay',require('../routes/promptpay'));app.use((err,req,res,next)=>res.status(err.status||500).send(err.message));server=app.listen(0);const base='http://localhost:'+server.address().port;
 browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1280,height:900}});await page.route('https://unpkg.com/**',r=>r.fulfill({contentType:'application/javascript',body:'window.lucide={createIcons(){}};'}));
 await page.goto(base+'/chef/recipes/create');await page.locator('[data-wizard-panel="0"]').waitFor();await page.locator('[name=title]').fill('Browser test recipe');await page.locator('[name=description]').fill('Description from browser');await page.locator('[name=duration]').fill('30');
 await page.locator('[data-recipe-image-file]').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j1ioAAAAASUVORK5CYII=','base64')});await page.waitForFunction(()=>document.querySelector('[name=image]').value.startsWith('/uploads/recipes/'));uploaded=await page.locator('[name=image]').inputValue();
 await page.locator('[data-wizard-next]').click();await page.locator('[name=ingredientName]').fill('Rice');await page.locator('[name=ingredientAmount]').fill('1 cup');await page.locator('[data-add=ingredient]').click();await page.locator('[name=ingredientName]').nth(1).fill('Water');await page.locator('[name=ingredientAmount]').nth(1).fill('2 cups');await page.locator('[data-wizard-next]').click();await page.locator('[name=stepDescription]').fill('Cook the rice');await page.locator('[data-wizard-back]').click();assert.equal(await page.locator('[name=ingredientName]').first().inputValue(),'Rice');await page.locator('[data-wizard-next]').click();
 await fs.mkdir('node_modules/.cache',{recursive:true});await page.screenshot({path:'node_modules/.cache/recipe-editor-desktop.png'});await page.locator('[data-wizard-save]').click();await page.waitForURL(/saved/);await page.locator('.recipe-local-detail').waitFor();assert((await page.locator('.recipe-local-detail').textContent()).includes('Description from browser'));assert.equal(await page.locator('.recipe-modal-close[data-close-recipe]').filter({visible:true}).count(),1);
 await page.locator('.recipe-modal-close[data-close-recipe]').filter({visible:true}).click();await page.locator('a[href$="/edit"][data-recipe-modal=form]').first().click();await page.locator('[data-wizard-panel="0"]').waitFor();assert.equal(await page.locator('.recipe-modal-close[data-close-recipe]').filter({visible:true}).count(),1);await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const close=page.locator('#recipe-content-dialog > .recipe-modal-close');const before=await close.boundingBox();await page.locator('#recipe-modal-content').evaluate(el=>el.scrollTop=el.scrollHeight);const after=await close.boundingBox();assert(Math.abs(before.y-after.y)<1);await page.locator('#recipe-modal-content').evaluate(el=>el.scrollTop=0);await page.screenshot({path:'node_modules/.cache/recipe-editor-mobile.png'});await require('../models/Client').collection.insertOne({_id:2,email:'two@example.test',name:'Buyer',role:'user'});await require('../models/Recipe').collection.insertOne({_id:99,publisher:1,title:'Paid browser recipe',category:'Thai',price:60,ingredients:[{name:'Secret rice',amount:'1 cup'}],steps:[{description:'Cook secret rice'}]});session.userId=2;
 await page.goto(base+'/recipes?source=chef');assert.equal(await page.locator('.nav-menu').isVisible(),false);await page.locator('.nav-mobile-toggle').click();assert.equal(await page.locator('.nav-menu').isVisible(),true);await page.keyboard.press('Escape');assert.equal(await page.locator('.nav-menu').isVisible(),false);const navHeight=await page.locator('.navbar').evaluate(el=>el.getBoundingClientRect().height);assert(navHeight<=74);await page.locator('a[href="/recipes/99"]').first().click();await page.locator('[data-purchase-recipe="99"]').waitFor();await page.locator('[data-purchase-recipe="99"]').click();await page.locator('.recipe-demo-checkout').waitFor();assert((await page.locator('.recipe-demo-checkout').textContent()).includes('ไม่มีการเรียกเก็บเงินจริง'));await page.locator('[data-confirm]').click();await page.locator('.recipe-local-detail .recipe-ingredients').waitFor();assert((await page.locator('.recipe-ingredients').textContent()).includes('Secret rice'));assert.equal(await page.locator('.recipe-modal-close[data-close-recipe]').filter({visible:true}).count(),1);
process.env.OMISE_MODE='test';process.env.OMISE_SECRET_KEY='skey_test_browser';const gateway=require('../services/omiseGateway');let charge,qrCreates=0;
 gateway.createCharge=async order=>{qrCreates++;charge={object:'charge',id:'chrg_test_browser',amount:order.amount,currency:'thb',livemode:false,metadata:{orderId:order._id},source:{type:'promptpay',scannable_code:{image:{download_uri:'https://api.omise.co/browser-test.svg'}}},status:'pending',paid:false,expires_at:new Date(Date.now()+900000).toISOString()};return charge};gateway.retrieveCharge=async()=>charge;
 await require('../models/Recipe').collection.insertOne({_id:100,publisher:1,title:'QR browser recipe',category:'Thai',price:80,ingredients:[{name:'QR unlock rice',amount:'1'}],steps:[{description:'Cook'}]});
 await page.route('https://api.omise.co/browser-test.svg',route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="240" height="240"><rect width="240" height="240" fill="white"/><text x="20" y="120">QR test fixture</text></svg>'}));
 await page.goto(base+'/recipes?source=chef');await page.locator('a[href="/recipes/100"]').first().click();await page.locator('[data-purchase-recipe="100"]').click();await page.locator('.recipe-promptpay-checkout').waitFor();assert.equal(await page.locator('.recipe-qr-mode').count(),0);await page.locator('[data-create-qr]').click();await page.locator('.recipe-qr-box img').waitFor();assert.equal(await page.locator('[data-create-qr]').isVisible(),false);assert(!await page.locator('.recipe-local-detail .recipe-ingredients').count());await page.screenshot({path:'node_modules/.cache/promptpay-mobile.png'});const originalExpiry=charge.expires_at;await page.locator('.recipe-qr-close').click();await page.locator('[data-purchase-recipe="100"]').click();await page.locator('.recipe-qr-box img').waitFor();assert.equal(qrCreates,1);assert.equal(charge.expires_at,originalExpiry);assert.equal(await page.locator('[data-create-qr]').isVisible(),false);charge={...charge,status:'successful',paid:true};await page.locator('.recipe-local-detail .recipe-ingredients').waitFor({timeout:20000});assert((await page.locator('.recipe-ingredients').textContent()).includes('QR unlock rice'));console.log('PASS: desktop/mobile editor, demo checkout and pending QR -> verified payment -> unlock');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));await mongoose.disconnect();if(db)await db.stop();if(uploaded&&/^\/uploads\/recipes\/[a-f0-9]{32}\.png$/.test(uploaded))await fs.unlink(path.join(process.cwd(),'public',uploaded)).catch(()=>{});});
