const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs/promises'),express=require('express'),mongoose=require('mongoose'),{MongoMemoryServer}=require('mongodb-memory-server'),{chromium}=require('playwright');
let db,server,browser,uploaded;
(async()=>{
 process.env.RECIPE_DEMO_PAYMENTS='true';process.env.NODE_ENV='test';
 db=await MongoMemoryServer.create();await mongoose.connect(db.getUri());await require('../models/Client').collection.insertOne({_id:1,email:'one@example.test',name:'Test chef',role:'chef',bio:'Test bio',institution:'Test school'});
 const app=express();app.set('views',path.resolve('views'));app.set('view engine','ejs');app.use(express.json());app.use(express.urlencoded({extended:false}));app.use(express.static(path.resolve('public')));const session={userId:1};app.use((req,res,next)=>{req.session=session;res.locals.currentUser={_id:1,name:'Test chef',role:'chef'};next()});app.use('/chef/recipes',require('../routes/chefRecipes'));app.use('/recipes',require('../routes/recipes'));app.use((err,req,res,next)=>res.status(err.status||500).send(err.message));server=app.listen(0);const base='http://localhost:'+server.address().port;
 browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1280,height:900}});await page.route('https://unpkg.com/**',r=>r.fulfill({contentType:'application/javascript',body:'window.lucide={createIcons(){}};'}));
 await page.goto(base+'/chef/recipes/create');await page.locator('[data-wizard-panel="0"]').waitFor();await page.locator('[name=title]').fill('Browser test recipe');await page.locator('[name=description]').fill('Description from browser');await page.locator('[name=duration]').fill('30');
 await page.locator('[data-recipe-image-file]').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j1ioAAAAASUVORK5CYII=','base64')});await page.waitForFunction(()=>document.querySelector('[name=image]').value.startsWith('/uploads/recipes/'));uploaded=await page.locator('[name=image]').inputValue();
 await page.locator('[data-wizard-next]').click();await page.locator('[name=ingredientName]').fill('Rice');await page.locator('[name=ingredientAmount]').fill('1 cup');await page.locator('[data-add=ingredient]').click();await page.locator('[name=ingredientName]').nth(1).fill('Water');await page.locator('[name=ingredientAmount]').nth(1).fill('2 cups');await page.locator('[data-wizard-next]').click();await page.locator('[name=stepDescription]').fill('Cook the rice');await page.locator('[data-wizard-back]').click();assert.equal(await page.locator('[name=ingredientName]').first().inputValue(),'Rice');await page.locator('[data-wizard-next]').click();
 await fs.mkdir('node_modules/.cache',{recursive:true});await page.screenshot({path:'node_modules/.cache/recipe-editor-desktop.png'});await page.locator('[data-wizard-save]').click();await page.waitForURL(/saved/);await page.locator('.recipe-local-detail').waitFor();assert((await page.locator('.recipe-local-detail').textContent()).includes('Description from browser'));assert.equal(await page.locator('.recipe-modal-close[data-close-recipe]').filter({visible:true}).count(),1);
 await page.locator('.recipe-modal-close[data-close-recipe]').filter({visible:true}).click();await page.locator('a[href$="/edit"][data-recipe-modal=form]').first().click();await page.locator('[data-wizard-panel="0"]').waitFor();assert.equal(await page.locator('.recipe-modal-close[data-close-recipe]').filter({visible:true}).count(),1);await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'node_modules/.cache/recipe-editor-mobile.png'});await require('../models/Client').collection.insertOne({_id:2,email:'two@example.test',name:'Buyer',role:'user'});await require('../models/Recipe').collection.insertOne({_id:99,publisher:1,title:'Paid browser recipe',category:'Thai',price:60,ingredients:[{name:'Secret rice',amount:'1 cup'}],steps:[{description:'Cook secret rice'}]});session.userId=2;
 await page.goto(base+'/recipes?source=chef');await page.locator('a[href="/recipes/99"]').first().click();await page.locator('[data-purchase-recipe="99"]').waitFor();await page.locator('[data-purchase-recipe="99"]').click();await page.locator('.recipe-demo-checkout').waitFor();assert((await page.locator('.recipe-demo-checkout').textContent()).includes('ไม่มีการเรียกเก็บเงินจริง'));await page.locator('[data-confirm]').click();await page.locator('.recipe-local-detail .recipe-ingredients').waitFor();assert((await page.locator('.recipe-ingredients').textContent()).includes('Secret rice'));assert.equal(await page.locator('.recipe-modal-close[data-close-recipe]').filter({visible:true}).count(),1);
 console.log('PASS: desktop/mobile editor, upload, preview/edit single close and simulated checkout unlock');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));await mongoose.disconnect();if(db)await db.stop();if(uploaded&&/^\/uploads\/recipes\/[a-f0-9]{32}\.png$/.test(uploaded))await fs.unlink(path.join(process.cwd(),'public',uploaded)).catch(()=>{});});
