const axios=require('axios');
const {createHmac,timingSafeEqual}=require('node:crypto');
function config(){const mode=process.env.OMISE_MODE||'test',key=process.env.OMISE_SECRET_KEY||'';if(!['test','live'].includes(mode)||!key.startsWith(mode==='live'?'skey_live_':'skey_test_'))throw Object.assign(new Error('ยังไม่ได้ตั้งค่า Omise '+mode+' key'),{status:503});if(mode==='test'&&process.env.NODE_ENV==='production')throw Object.assign(new Error('ปิดการทดสอบ QR ใน production'),{status:503});if(mode==='live'&&process.env.OMISE_LIVE_PAYMENTS!=='true')throw Object.assign(new Error('ยังไม่เปิดรับเงินจริง'),{status:503});if(mode==='live'&&!process.env.OMISE_WEBHOOK_SECRET)throw Object.assign(new Error('กรุณาตั้งค่า webhook secret ก่อนเปิดรับเงินจริง'),{status:503});return{key,livemode:mode==='live'};}
function configured(){try{config();return true}catch(_){return false}}
function client(){return axios.create({baseURL:'https://api.omise.co',timeout:15000,auth:{username:config().key,password:''},headers:{'Omise-Version':'2019-05-29'}});}
async function createCharge(order){const data=new URLSearchParams({amount:String(order.amount),currency:'thb','source[type]':'promptpay',description:'CookHub recipe '+order.recipeId,'metadata[orderId]':order._id,expires_at:new Date(Date.now()+15*60*1000).toISOString()});return(await client().post('/charges',data.toString(),{headers:{'Content-Type':'application/x-www-form-urlencoded'}})).data;}
async function retrieveCharge(id){if(!/^chrg_[a-zA-Z0-9_]+$/.test(id))throw Error('Invalid charge');return(await client().get('/charges/'+id)).data;}
async function retrieveEvent(id){if(!/^evnt_[a-zA-Z0-9_]+$/.test(id))throw Error('Invalid event');return(await client().get('/events/'+id)).data;}
function verifySignature(req){const secret=process.env.OMISE_WEBHOOK_SECRET;if(!secret)return false;const timestamp=req.get('Omise-Signature-Timestamp')||'';if(!/^\d+$/.test(timestamp)||Math.abs(Date.now()/1000-Number(timestamp))>300)return false;const expected=createHmac('sha256',Buffer.from(secret,'base64')).update(timestamp+'.').update(req.rawBody||Buffer.alloc(0)).digest();return(req.get('Omise-Signature')||'').split(',').some(value=>{if(!/^[a-fA-F0-9]{64}$/.test(value.trim()))return false;return timingSafeEqual(Buffer.from(value.trim(),'hex'),expected)});}
module.exports={config,configured,createCharge,retrieveCharge,retrieveEvent,verifySignature};
